package com.app.weather.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table "CITYS".
 */
/**

 * 采用GreenDao框架对本地数据进行增删改查
 * 封装大部分数据库操作方法
 * greenDAO是一个可以帮助Android开发者快速将Java对象映射到SQLite数据库的表单中的ORM解决方案，
 * 通过使用一个简单的面向对象API，开发者可以对Java对象进行存储、更新、删除和查询。
 * @data: 2019/5/25
 */

public class CitysDao extends AbstractDao<Citys, Long> {
    /*
     * CitysDao是对应于数据库表CITYS的Dao类，
     * 它封装了一个createTable()和dropTable()方法，
     * 其中createTable()方法用于执行创建CITYS表SQL语句；
     * dropTable()方法执行删除表CITYS表SQL语句。
     * 另外，由于GreenDao对本地数据库数据的增删改查操作均封装AbstractDao抽象类中
     * CitysDao通过继承的方式使其拥有了操作CITYS表数据的能力。
     */
    public static final String TABLENAME = "CITYS";//声明CITYS表
    /**
     * 城市实体的属性
     * 可用于查询生成器和引用列名称
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property City = new Property(1, String.class, "city", false, "CITY");
        public final static Property Weather = new Property(2, String.class, "weather", false, "WEATHER");
        public final static Property DuMax = new Property(3, String.class, "duMax", false, "DU_MAX");
        public final static Property DuMin = new Property(4, String.class, "duMin", false, "DU_MIN");
    }


    public CitysDao(DaoConfig config) {
        super(config);
    }
    
    public CitysDao(DaoConfig config, com.app.weather.bean.DaoSession daoSession) {
        super(config, daoSession);
    }

    /** 创建基础数据表  */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITYS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CITY\" TEXT," + // 1: city
                "\"WEATHER\" TEXT," + // 2: weather
                "\"DU_MAX\" TEXT," + // 3: duMax
                "\"DU_MIN\" TEXT);"); // 4: duMin
    }

    /** 删除基础数据库表 */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITYS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Citys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String duMax = entity.getDuMax();
        if (duMax != null) {
            stmt.bindString(4, duMax);
        }
 
        String duMin = entity.getDuMin();
        if (duMin != null) {
            stmt.bindString(5, duMin);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Citys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String duMax = entity.getDuMax();
        if (duMax != null) {
            stmt.bindString(4, duMax);
        }
 
        String duMin = entity.getDuMin();
        if (duMin != null) {
            stmt.bindString(5, duMin);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Citys readEntity(Cursor cursor, int offset) {
        Citys entity = new Citys( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // weather
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // duMax
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // duMin
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Citys entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeather(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDuMax(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDuMin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Citys entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Citys entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Citys entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
